### ISSUE TITLE
URL returned twice

### ISSUE THREAD

**Issue by impredicative** [lipoja/URLExtract#32] opened 2019-02-21 00:00 UTC
A URL was unexpectedly returned twice:

```python
>>> from urlextract import URLExtract
>>> ex = URLExtract()
>>> ex.find_urls('https://i2.wp.com/siliconfilter.com/wp-content/uploads/2011/06/Techmeme100-top-20.jpg')
['https://i2.wp.com/siliconfilter.com/wp-content/uploads/2011/06/Techmeme100-top-20.jpg', 'https://i2.wp.com/siliconfilter.com/wp-content/uploads/2011/06/Techmeme100-top-20.jpg']
```

**Comment by karlicoss** [comment] 2019-02-26 21:56
I think it happens due to duplicate '.com' in the URL, e.g. `site.com/subpath.com` is the minimal example to reproduce

**Comment by impredicative** [comment] 2019-02-26 22:00
If a URL is in a larger URL, my ideal requirement is that only the larger URL be returned. The inner one which here is `siliconfilter.com` should then be skipped. This criteria must apply recursively.

**Comment by lipoja** [comment] 2019-02-27 11:44
Thank you for reporting this issue. It looks like it is the same as issue #17 so I am closing this thread because it is duplicate.

**Closed by lipoja** 2019-02-27 11:44 UTC
Labels: duplicate
